### PR TITLE
Debian Package

### PR DESCRIPTION
**Pull request by martensms**
Hey there,

I made a debian package generator that would ease up installation for newbies.
You have to do these steps to have a really valid package, which I could not fulfill myself without further information:

**Important Notes**:

- Replace invalid email address (email@server.tld) in ./package/ubuntu/DEBIAN/control
- Replace invalid email address (email@server.tld) in ./package/ubuntu/root/usr/share/doc/howto/* files

- Version of the package is the VERSION variable in ./package.sh
- basics.py is now namespaced in /usr/lib/howto/basics.py. This is important, no execution flag anymore, no shebang in order to be debian package compliant. I added a `sys.path.append("/usr/lib/howto")` into the howto file.

- /usr/bin/* files are renamed to have no .py execution (debian package requirement), so this is a manual `mv` call inside the ./package.sh

- I did not remove the old shell scripts, if the package works we might not need them anymore.

The prototypical package seems to work, it currently has only the dependencies of python and python-bs4 (without any specific version). Let me know if it works for you, too.

Cheers from Germany,
Chris

### CODE REVIEW

**Comment by underscorejho** [comment]
This is awesome! I've never actually implemented this before, but I looked it over and I think I've got a good idea of what's going on.

A few questions so I'm clear:  

Wouldn't `sys.path.append("/usr/lib/howto")` append to PATH every time the script is run? Or does it check to see if that directory is in path, and append it otherwise?

This puts executables in a directory in PATH,  so `googlehowto` is not still a valid command? (It wouldn't really be a big deal, I'd just want to take it out of the README.md)

Other than that, I'll make the suggested changes later after I merge. Thanks!

**Comment by martensms** [comment]
It only appends it temporarily (as I could test it locally). So yeah, "googlehowto" is not a binary then.

But you could add a symlink creation in the postinstall files (./package/ubuntu/DEBIAN/postinst is a shell script) to create a symlink from /usr/bin/googlehowto to /usr/bin/ghowto or so.

You have to remember that everything that is changed in the filesystem inside a postinst (post-installation script) has to be removed in the prerm (pre-removal) file. But those scripts have to always return 0 as an exit code.

PS: So, imagine you setup a symlink on installation (postinst). If the symlink doesn't exist anymore on removal of the file (prerm), you have to do something like "rm /usr/bin/googlehowto || true;" in order to have a successful package removal.

**Comment by underscorejho** [comment]
For now we can just forget about `googlehowto`. 

It looks like if the directory `/usr/lib/howto` was in `PYTHONPATH`, it would be able to use it without that `sys` call. You could add lines to the `package.sh` similar to what's in `howto_install.sh` where it checks PATH for the directory and adds it if it's not there. But do it with PYTHONPATH instead of PATH.

But for now I'll merge this. Then we can work on improvements.

**Comment by underscorejho** [comment]
Check out the wiki page to make sure I got the instructions right.

**Comment by martensms** [comment]
I think it would be awesome if it was just in the Releases page, so people can just download and install the .deb file without any compilation step.

For example, atom uploaded the deb files here: https://github.com/atom/atom/releases

I think there should be a manual Upload feature there to host the deb file. I haven't used it yet because my other projects are way beyond 250MB (architecture dependent) - they all have runtimes shipped with 'em, but I wanted to try it out next release :)

**Pull request merged**
